// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMq1ND53Nz2ppE2RUzRwC1DMBo0aLxDDQ',
    appId: '1:1088759553715:web:27212f1cdceb8af5281ac6',
    messagingSenderId: '1088759553715',
    projectId: 'voteapplipushnotification',
    authDomain: 'voteapplipushnotification.firebaseapp.com',
    storageBucket: 'voteapplipushnotification.appspot.com',
    measurementId: 'G-ZB0FBRT2J5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-X0jb6LVEAV7kA6JANFRMlNjUlskbRq8',
    appId: '1:1088759553715:android:dd539f9e7dcab50c281ac6',
    messagingSenderId: '1088759553715',
    projectId: 'voteapplipushnotification',
    storageBucket: 'voteapplipushnotification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYRpZ4y1a3vAvgxxJSoKqk9ehMs7OQyfc',
    appId: '1:1088759553715:ios:bc3123125fca294a281ac6',
    messagingSenderId: '1088759553715',
    projectId: 'voteapplipushnotification',
    storageBucket: 'voteapplipushnotification.appspot.com',
    iosBundleId: 'com.example.flutterVote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYRpZ4y1a3vAvgxxJSoKqk9ehMs7OQyfc',
    appId: '1:1088759553715:ios:ee0e4cbdc6955ac1281ac6',
    messagingSenderId: '1088759553715',
    projectId: 'voteapplipushnotification',
    storageBucket: 'voteapplipushnotification.appspot.com',
    iosBundleId: 'com.example.flutterVote.RunnerTests',
  );
}
